security:
  encoders:
    # this internal class is used by Symfony to represent in-memory users
    Symfony\Component\Security\Core\User\User: 'bcrypt'
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    backend_users:
      memory:
        users:
          admin: { password: '', roles: ['ROLE_ADMIN'] }
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api:
      pattern: ^/api
      anonymous: false
      security: true
      stateless: true
      methods: [POST, PUT, PATCH]
      guard:
        authenticators:
        - App\Security\TokenAuthenticator
    main:
      anonymous: true
      security: false
      stateless: true


#  access_control:
#    - { path: ^/api, methods: [POST, PUT, PATCH] }
