resources:

  App\Entity\ValueCollection:
    itemOperations: []
    collectionOperations:
      post:
        method: 'POST'
        path: '/batch-values'
        controller: App\Controller\PostBatchValuesAction
        read: false
        openapi_context:
          summary: 'Create batch of values'
          tags: ['Value']
          requestBody:
            required: true
            content:
              application/ld+json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Value:jsonld-valueWrite'
          responses:
            '201':
              description: 'Batch of values created'
              content:
                application/ld+json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/Value:jsonld-valueRead'
            '400':
              description: 'Invalid input'
